maximum_name_email: 50
minimum_password: 6
size_avatar: 50
size_picture_book: 100
per_page: 10
per_page_book: 9
per_page_review: 6
number_increment_page: 1
max_num_page: 5000
min_num_page: 20
length_show: 60
accept_image: "image/jpeg,image/gif,image/png"
star_rate_html: "<i class='glyphicon glyphicon-star'></i>"
asc_value_star: 1
init_count: 0
maximum_introduction: 1000
date: "%B %Y"
date_time: "%d %B %Y - %H : %M"
first_element: 0
one_star: 1
two_star: 2
three_star: 3
four_star: 4
five_star: 5
